// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBOd5DiomzBzwUK_60VWtYgWHwjLNYoBU0',
    appId: '1:541274176806:web:821f0bce8168b0a03855e7',
    messagingSenderId: '541274176806',
    projectId: 'pushnotificationapp-37baa',
    authDomain: 'pushnotificationapp-37baa.firebaseapp.com',
    storageBucket: 'pushnotificationapp-37baa.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAiLP3kG57K06PGm0GVVQ2TC12Fjsh7fEA',
    appId: '1:541274176806:android:03752e56c94a380c3855e7',
    messagingSenderId: '541274176806',
    projectId: 'pushnotificationapp-37baa',
    storageBucket: 'pushnotificationapp-37baa.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCApn9jurKlBlWQZr_qjYxDh_hQ-B1LWhk',
    appId: '1:541274176806:ios:9bce4765f1100ac43855e7',
    messagingSenderId: '541274176806',
    projectId: 'pushnotificationapp-37baa',
    storageBucket: 'pushnotificationapp-37baa.firebasestorage.app',
    iosBundleId: 'com.example.pushNotifications',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCApn9jurKlBlWQZr_qjYxDh_hQ-B1LWhk',
    appId: '1:541274176806:ios:9bce4765f1100ac43855e7',
    messagingSenderId: '541274176806',
    projectId: 'pushnotificationapp-37baa',
    storageBucket: 'pushnotificationapp-37baa.firebasestorage.app',
    iosBundleId: 'com.example.pushNotifications',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBOd5DiomzBzwUK_60VWtYgWHwjLNYoBU0',
    appId: '1:541274176806:web:8e5a7e6e98cfe4cd3855e7',
    messagingSenderId: '541274176806',
    projectId: 'pushnotificationapp-37baa',
    authDomain: 'pushnotificationapp-37baa.firebaseapp.com',
    storageBucket: 'pushnotificationapp-37baa.firebasestorage.app',
  );
}
